### ISSUE TITLE
13 things video addition

### ISSUE THREAD

**Issue by ChrisThePCGeek** [techno-tim/youtube-videos#13]
to disable auto-rebooting edit /etc/apt/apt.conf.d/50unattended-updrades

uncomment this line:
//Unattended-Upgrade::Automatic-Reboot "false";

**Comment by timothystewart6** [comment]
Thank you!  Will add this soon!

**Comment by qskwood** [comment]
See #17 for a fix

**Comment by timothystewart6** [comment]
Thank you!
