### ISSUE TITLE
Wrong readme file for Windows Developer Setup

### ISSUE THREAD

**Issue by Jorgen1040** [techno-tim/youtube-videos#3]
The readme file in the forlder for Windows Developer Setup is for "How to Virtualize Your Home Router / Firewall Using pfSense", which is obviously not the right one. 
Would love to have the right commands/written walkthrough of the Windows developer setup.

**Comment by timothystewart6** [comment]
Thank you!  I'll fix this!

**Comment by timothystewart6** [comment]
fixed by https://github.com/techno-tim/youtube-videos/commit/db99f1fdfe342fe7aa7b0b9eb7ccab283c1a953d

**Comment by timothystewart6** [comment]
All set @Jorgen1040 !  Fixed the docs.  Thanks!
