### ISSUE TITLE
Multiple VLANs on bridge

### ISSUE THREAD

**Issue by cmonty14** [techno-tim/youtube-videos#43]
Hi,
this is a question related to "first-11-things-proxmox".
You provide a config with multiple VLANs on a single bridge (+ bond).

Question:
What must be configured to get dedicated network (subnets) on a VLAN, e.g.
VLAN 2
192.168.2.0/24
VLAN 3
192.168.3.0/24
VLAN 10
192.168.10.0/24
and a working routing if the main network of Proxmox Server is in 192.168.1.0/24?

Or will this only work with [OVS](https://pve.proxmox.com/wiki/Open_vSwitch)?

THX

**Comment by timothystewart6** [comment]
Hi!  This doesn't look like an issue with the repo but a general question.  Feel free to join our Discord community and ask there!  https://discord.gg/DJKexrJ
