### ISSUE TITLE
AI Training Script for running TensorFlow container 

### ISSUE THREAD

**Issue by apulache** [techno-tim/youtube-videos#6]
Hi Tim, how are you?

I've just completed this tutorial on my homelab and worked  like a charm!!!

Nevertheless, there is something missing from de video and for the documentation which is actually how to call the script to initialized the AI training that you mentioned on video (at 6:51 min).

I've looked at dockerhub and there is no details on how to run this image.

I'll really appreciate you share the details.

Thanks in advance!!!

**Comment by timothystewart6** [comment]
Hi there!  I will add it shortly!  Thank you!

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/youtube-videos/commit/3a88a8608e9ffc19034a69aa829195fbed3e9eb4
