### ISSUE TITLE
typo in first 13 things video doc

### ISSUE THREAD

**Issue by ChrisThePCGeek** [techno-tim/youtube-videos#8]
there is a typo in the apt commands for updating system software on the first 13 things video documentation. it says apt-apt

a suggestion for timezone config is also to use dpkg-reconfigure tzdata for a menu based selection of time zones

**Comment by timothystewart6** [comment]
Thank you!  Fixed in https://github.com/techno-tim/youtube-videos/commit/2d40241a841d9fb55efc56d698440ed84b4e18ee
